GET http://localhost:3003/api/blogs

###
POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Brendan Allison",
    "title": "Yet another backend note  cypress 4",
    "url": "http://cypress.com",
    "likes": 1
}

###
POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Tommy Hilfieger",
    "title": "The building of another note cypress 2",
    "url": "http://gogcypress.com",
    "likes": 1
}

###
POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "John Brown",
    "title": "Yet another note cypress 3",
    "url": "http://gogcypress.com",
    "likes": 1
}

###
POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Kelson Brandy",
    "title": "Programming in python",
    "url": "http://pythondo.com",
    "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The old async",
    "author": "Mycone James",
    "url": "www.goasync.com"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The adventure of Venturi",
    "author": "Albert Swindon",
    "url": "www.swindonync.com",
    "likes": 8
}

###
GET http://localhost:3003/api/blogs/628f671e7acf608b48f4d437

###
GET http://localhost:3003/api/blogs/628f7a627acf608b48f4d43d

###
DELETE http://localhost:3003/api/blogs/628f7a627acf608b48f4d43d

###
DELETE http://localhost:3003/api/blogs/62w23a627acf345b48f42w34

###
DELETE http://localhost:3003/api/blogs/628f7a627acf608b48f4d23d

###
DELETE http://localhost:3003/api/blogs/628f7a627acf608s23f4d43d

###
DELETE http://localhost:3003/api/blogs/628f7a627acf68f4d43d

### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen",
    "name": "Matti Luukkainen"
}

### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "salainen",
    "name": "Superuser"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "",
    "password": "salainen",
    "name": "Great Superuser"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "http://swindonync.com",
    "title": "Twelve hills without slope 3",
    "author": "Brandon Williams"
}

### Get all users
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

 {
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

 {
    "username": "mluukkai",
    "password": "salainen"
}